use leptos::prelude::*;

#[component]
pub fn Index() -> impl IntoView {
    view! {
        <div class="row justify-content-center">
            <div class="col-sm-8 col-md-8">
                <div class="p-4 mt-4 mb-4 bg-body-secondary rounded-3">
                    <div class="container-fluid py-5">
                        <h1 class="display-5 fw-bold">{"Welcome to egcode"}</h1>
                        <p class="col-md-8 fs-4">
                            {"Encrypting and signing gcode by users, devices and device owners."}
                            <br /> {"Protecting our Engineering Intellectual Property."}
                        </p>
                    </div>
                </div>
                <p>
                    <strong>{"egcode"}</strong>
                    {" is a Rust crate and standard being developed by the Design and Manufacturing Futures Lab at the University of Bristol
                    as part of their future manufacturing supply chains research. Gcode is the industry standard code that
                    details the manufacturing instructions that bring our digital designs to reality. It is ascii plaintext
                    and used by almost all additive and subtractive manufacturing processes.
                    "}
                </p>
                <p>
                    {"Have a go today by using the encrypt and decrypt pages on this site! You can even connect to a printer and test the entire workflow!"}
                </p>
                <p>
                    {"Makerspaces commonly have USB sticks lying around for people load their gcode onto the machines and cloud services
                    offer methods to store and submit jobs remotely. Gcode does not offer any protection around who can use your IP. Anyone
                    with access to the USB stick could easily take your file and print it for themselves and on any number of machines. They
                    could also reverse engineer the design and then build on your hard work."}
                </p>
                <p>
                    {"You also have no control over what the cloud services are doing with you data. They could easily be manufacturing variants of
                    your designs and training AI on your IP. You have no control over it once it has been sent."}
                </p>
                <p>
                    {"Machine owners have to also develop their own processes to manage who's allowed to machine what on what device. These processes
                    can be difficult to set up and manage. Especially in educational environments where you want students to interact and work with
                    the machines to appreciate how they operate."}
                </p>
                <p>
                    <strong>{"egcode"}</strong>
                    {" overcomes this by providing the tools and standard for encrypting and signing gcode files.
                    The standard offers multiple levels of encryption including:"}
                </p>
                <ul>
                    <li>
                        <strong>{"Password"}</strong>
                        {" A user password protects the gcode and has to enter the password on the device for it to be able to decrypt and process the gcode."}
                    </li>
                    <li>
                        <strong>{"Device Key"}</strong>
                        {" A user protects the gcode by using a device's public key coupled with an ephmeral private-public key-pair
                        generated by egcode. The file can then only be decrypted by the device with the associated device private key."}
                    </li>
                    <li>
                        <strong>{"Password and Device Key"}</strong>
                        {" A user protects their gcode with both a password and device public key. To use the code the user needs to be present at the right machine thereby
                        providing a double lock."}
                    </li>
                </ul>
                <p>
                    {"egcode is in alpha and we're keen to work with industry and education to evolve the standard. Our roadmap includes additional locks and signatures to
                    ensure the integrity of IP and the appropriate permissions have been granted to enable gcode to be submitted to devices. "}
                    <strong>
                        {"Please get in "}
                        <a href="mailto:james.gopsill@bristol.ac.uk">{"contact"}</a>
                        {" to learn more."}
                    </strong>
                </p>
                <p>{"Research"}</p>
                <ul>
                    <li>
                        {"Using Web3.0 to build trust in agent-based additive manufacturing systems. J Gopsill, P Walker-Davies Procedia CIRP 134, 687-692"}
                    </li>
                    <li>
                        {"Secure by design: exploring a minimal Web3.0 trust network to provide de-centralised secure, private, and provenance preserving design and manufacture workflows. J Gopsill, O. Schiffmann, C. Ranscombe and M. Goudswaard. Proceedings of DESIGN. 2026"}
                    </li>
                </ul>
            </div>
        </div>
    }
}
